### ISSUE TITLE
“Don't run Bundler as root.”

### ISSUE THREAD

**Issue by elia** [docker-library/rails#10]
Maybe it can be solved by [using `--system`](https://github.com/docker-library/ruby/blob/master/2.1/onbuild/Dockerfile#L8)

Also IIRC avoiding to run as root inside the container's a good practice security-wise (I may be wrong or out of date tho)

**Comment by yosifkit** [comment]
This is just a warning. Closing for now. Feel free to post new information if I am wrong.

**Comment by Arcrammer** [comment]
So how do we get past the message, then?

**Comment by kilianc** [comment]
+1

**Comment by Arcrammer** [comment]
@kilianc I've figured out how to install Rails in Docker, although I don't completely understand which part of my Dockerfile is leveraging this problem. Anyway! <a href="https://gist.github.com/Arcrammer/028c83e687746fd6d80d">Here's my Dockerfile</a>.

If you can get this to work let me know and if you can figure out how it helps me bypass this problem I'd appreciate it.

**Comment by kilianc** [comment]
@Arcrammer probably changing your $HOME does the trick

**Comment by cbliard** [comment]
From [bundler 1.11.0.pre.1 (2015-11-29)](https://github.com/bundler/bundler/blob/master/CHANGELOG.md#1110pre1-2015-11-29), there is a `silence_root_warning` setting to silence the warning when `bundle install` is run as root.

So to remove the warning, add this to your Dockerfile:

```
RUN bundle config --global silence_root_warning 1
```
