### ISSUE TITLE
Don't install rmagick gem

### ISSUE THREAD

**Issue by meonthewire** [docker-library/rails#16]
rmagick gem insn't installed even with all dependencies.

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

```
/usr/local/bin/ruby extconf.rb 
```

checking for Ruby version >= 1.8.5... yes
checking for gcc... yes
checking for Magick-config... no
Can't install RMagick 0.0.0. Can't find Magick-config in /usr/local/bundle/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

**\* extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
    --with-opt-dir
    --without-opt-dir
    --with-opt-include
    --without-opt-include=${opt-dir}/include
    --with-opt-lib
    --without-opt-lib=${opt-dir}/lib
    --with-make-prog
    --without-make-prog
    --srcdir=.
    --curdir
    --ruby=/usr/local/bin/ruby

extconf failed, exit code 1

Gem files will remain installed in /usr/local/bundle/gems/rmagick-2.13.3 for inspection.
Results logged to /usr/local/bundle/extensions/x86_64-linux/2.1.0-static/rmagick-2.13.3/gem_make.out
An error occurred while installing rmagick (2.13.3), and Bundler cannot
continue.
Make sure that `gem install rmagick -v '2.13.3'` succeeds before bundling.
Service 'web' failed to build: The command [/bin/sh -c bundle install] returned a non-zero code: 5

**Comment by ehsan6sha** [comment]
accroding to this link:
https://github.com/rmagick-temp/rmagick/issues/133

the correct config path was /usr/lib/x86_64-linux-gnu/ImageMagick-6.8.9/bin-Q16/Magick-config and adding a link to it in /usr/bin/ using the command below solved my problem on ubuntu 15
ln -s /usr/lib/x86_64-linux-gnu/ImageMagick-6.8.9/bin-Q16/Magick-config /usr/bin/Magick-config

**Comment by bf4** [comment]
@ehsan6sha that's the old repo.  Thanks for sharing

**Comment by cvijay1985** [comment]
RUN apt-get update
RUN apt-get install -y software-properties-common
RUN apt-get install -y python-software-properties
RUN add-apt-repository ppa:brightbox/ruby-ng
RUN apt-get update && apt-get install -y ruby2.2 ruby2.2-dev ruby-bundler
RUN apt-get update && apt-get install -y git-core curl zlib1g-dev build-essential libssl-dev libreadline-dev libyaml-dev libsqlite3-dev sqlite3 libxml2-dev libxslt1-dev libcurl4-openssl-dev python-software-properties libffi-dev
RUN rm -rf /var/lib/apt/lists/*
RUN apt-get install imagemagick libmagickcore-dev libmagickwand-dev
RUN gem install bundler
RUN gem install nokogiri
RUN gem install nokogiri-diff
RUN gem install rmagick

**Comment by cvijay1985** [comment]
Hi get same problem when i run the rmagick. but i get solution form below using command.

RUN apt-get install imagemagick libmagickcore-dev libmagickwand-dev
RUN gem install rmagick
