### ISSUE TITLE
rails:onbuild does not work with engines in subfolders

### ISSUE THREAD

**Issue by wnkz** [docker-library/rails#19]
Hi,
In our Rails application we have engines which are referenced in our `Gemfile` e.g:

```
gem 'foo', path: 'engines/foo'
```

This is problematic since the `rails:onbuild` image does `ONBUILD COPY . /usr/src/app` **after** `ONBUILD RUN bundle install` hence producing this kind of error:

```
The path `/usr/src/app/engines/foo` does not exist.
2014/12/17 11:15:48 The command [/bin/sh -c bundle install] returned a non-zero code: 13
```

I am **not** an expert at Rails apps but I think this is a *common* practice ; I there a specific reason I don't know about for running `bundle install` **before** copying the files ?
Can someone tell me if we are doing something wrong with our `Gemfile` ?

If there is no specific reason, since `Gemfile` and `Gemfile.lock` are generally kept under version control, I'd suggest to replace:

```
ONBUILD COPY Gemfile /usr/src/app/
ONBUILD COPY Gemfile.lock /usr/src/app/
ONBUILD RUN bundle install

ONBUILD COPY . /usr/src/app
```

by

```
ONBUILD COPY . /usr/src/app
ONBUILD RUN bundle install
```

Tell me what you think ; I'd be pleased to make a PR for this.

**Comment by wnkz** [comment]
:+1: Make sense, thank you for your answer, sorry I forgot to reply and close !

**Comment by louy2** [comment]
In the same spirit can the `apt-get update && apt-get install` also be cached if they are put before `COPY . /usr/src/app`?
