### ISSUE TITLE
Rails 4.2 Not Accessible on Host

### ISSUE THREAD

**Issue by johnallen3d** [docker-library/rails#20]
I used the `onbuild` image to create a new Rails 4.2 application but was having difficulty accessing it (Boot2Docker on OSX). It turns out there was [a change with the release 4.2](http://edgeguides.rubyonrails.org/4_2_release_notes.html#default-host-for-rails-server) so that by default in development mode applications listen on `localhost` vs `0.0.0.0`. Essentially this means (to the best of my understanding) that the web server is only accessible from inside of the running container. In order to access my server externally (ie. on the host machine) I had to do something like: `rails s -b 0.0.0.0` Perhaps this option should be added to the [default command in the `onbuild` image](https://github.com/docker-library/rails/blob/master/onbuild/Dockerfile#L19)?

**Comment by tianon** [comment]
Ugh, yeah, I guess we have to.

**Comment by tianon** [comment]
As a side note, thanks for doing the digging for why/where this happened!

**Comment by yosifkit** [comment]
Well, technically the `onbuild` tag does not assume a version of rails and just installs the version from the gemfile.

**Comment by tianon** [comment]
True, but this change would still be backwards-compatible, right?

**Comment by yosifkit** [comment]
AFAIK, yeah this is fine. Unless someone can point out where there was no `-b ipAddress` in `rails s`.

**Comment by johnallen3d** [comment]
I was trying to come up with a clever way to quickly spin up Docker containers with older Rails versions to prove this out but ran into roadblocks with different versions of Bundler in older generated gemfiles...

Anyway, I was able to trace the [`-b` option back to Rails 1.2](https://github.com/rails/rails/blob/1-2-stable/railties/lib/commands/servers/webrick.rb) (the oldest branch on GitHub). More specifically it was introduced in [a commit](https://github.com/rails/rails/commit/e85e58f7a9a0989e1f729ad2c1d453fa438155ac) on a date prior to the release of [`1.0`](https://rubygems.org/gems/rails/versions/1.0.0).

Pull request forthcoming.
