### ISSUE TITLE
ONBUILD conflicts with items that need to be installed first

### ISSUE THREAD

**Issue by MisinformedDNA** [docker-library/rails#28]
ONBUILD is running "bundle install" as soon as my Dockerfile is run. This appears to be correct behavior.

But one of my gems, 'tiny_tds' requires 'freetds' it to be installed first. I can't install it first because ONBUILD is running first. The same thing would happen if Postgres or MySQL were not installed before the bundle install.

Is there a way to handle this scenario?

**Comment by yosifkit** [comment]
This is the limitation of the onbuild images.  They are meant for simple projects to just get you running.  For more complicated setups that require something to be installed by apt beforehand, we recommend  just copying the items from the onbuild Dockerfile, removing `ONBUILD` from the commands, and then adding in your custom steps.
