### ISSUE TITLE
Can this be used in production?

### ISSUE THREAD

**Issue by TimPerry** [docker-library/rails#32]
Am I correct in saying this uses web brick? And if so does this mean that is should not be used in production?

Thanks in advance

Tim

**Comment by md5** [comment]
It depends on what's in your `Gemfile`. If you have something like `puma` in there, it should get used automatically, just like it does when running `rails server` does in a non-Docker setup.

**Comment by TimPerry** [comment]
@md5 Currently no, but sounds like would be a good idea. Thanks for getting back to me.
