### ISSUE TITLE
Ruby 2.3

### ISSUE THREAD

**Issue by mustela** [docker-library/rails#35]
Is there any plan to use ruby 2.3? 

Thanks

**Comment by yosifkit** [comment]
Ah, it just needs a bump in the [update script](https://github.com/docker-library/rails/blob/c4fa43cb58579cc03e0616042beb7aa7a10a7c24/update.sh#L4).

**Comment by Yanchek99** [comment]
When can this happen?  Would it be better to make this configurable?

**Comment by Yanchek99** [comment]
@yosifkit This can be closed as PR #40 took care of this.  It would be nice if we could somehow pass in a Ruby version.
