### ISSUE TITLE
'Connection timed out' with bundle install

### ISSUE THREAD

**Issue by ctammes** [docker-library/rails#39]
I ran into this error on a company server probably protected by proxy and firewall. I could not change the configuration. This was the error output:
```
fatal: unable to connect to github.com:
github.com[0: 192.30.252.128]: errno=Connection timed out

Retrying git clone 'git://github.com/rweng/jquery-datatables-rails.git' "/usr/local/bundle/cache/bundler/git/jquery-datatables-rails-b8d699e208e47fe51869a7aebe3d593ff0672f4a" --bare --no-hardlinks --quiet due to error (2/4): Bundler::Source::Git::GitCommandError Git error: command `git clone 'git://github.com/rweng/jquery-datatables-rails.git' "/usr/local/bundle/cache/bundler/git/jquery-datatables-rails-b8d699e208e47fe51869a7aebe3d593ff0672f4a" --bare --no-hardlinks --quiet` in directory /usr/src/app has failed.
```

I could solve this by globally change git:// into https:// in the Dockerfile before the ONBUILD instructions:
```
# solves 'Connection time out' on server in company domain.
RUN git config --global url."https://".insteadOf git://
```

I do not know if this works in all situations, however.

**Comment by yosifkit** [comment]
There is no way to run your own items before the `ONBUILD` steps trigger. If you need customization before the `ONBUILD` instructions happen, then that would be the perfect opportunity for no longer using the `onbuild` tag and instead copying what you need from the onbuild Dockerfile and adding in your steps as described in the [`rails:onbuild` section](https://hub.docker.com/_/rails/) of the description.
