### ISSUE TITLE
The rails account in Docker Hub

### ISSUE THREAD

**Issue by fxn** [docker-library/rails#42]
Hi, I have tried to figure this out through different channels without luck. Let my try here, but feel free to close if you can't help.

I am a Rails core team member, and want to register a "rails" account to share an image for Rails core development. That is, someone willing to contribute a patch to Rails would fetch the image and create containers where all is set to tinker and run the test suites. This would be an alternative to our current [rails-dev-box](https://github.com/rails/rails-dev-box). As you see it has a different goal than this official rails image.

Docker Hub says the "rails" username is taken (same for an organization namespace), but https://hub.docker.com/u/rails/ yields a 404. Could it be the case that Docker Hub disallows accounts named as one of their official repositories?

**Comment by tianon** [comment]
I don't _think_ that's the case, but I think reaching out to
support@docker.com is probably the fastest way to find out (unfortunately
we don't have any visibility into things like that).  Sounds like a cool
project though!

**Comment by fxn** [comment]
Awesome, thanks!
